"""empty message

Revision ID: 801fed6c9695
Revises: 5b3955393f5a
Create Date: 2023-06-20 06:51:42.730304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '801fed6c9695'
down_revision = '5b3955393f5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('phone_number',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=10),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('phone_number',
               existing_type=sa.Numeric(precision=10),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
