"""empty message

Revision ID: df71185521dc
Revises: 801fed6c9695
Create Date: 2023-06-19 22:05:08.306518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df71185521dc'
down_revision = '801fed6c9695'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friends',
    sa.Column('userA_id', sa.Integer(), nullable=False),
    sa.Column('userB_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['userA_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['userB_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('userA_id', 'userB_id'),
    sa.UniqueConstraint('userA_id', 'userB_id'),
    created_at=Column(None, Date(), table=None, nullable=False, default=ColumnDefault(datetime.date(2023, 6, 19)))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('friends')
    # ### end Alembic commands ###
