"""empty message

Revision ID: 5b3955393f5a
Revises: 9be253d75564
Create Date: 2023-06-17 14:24:17.358961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b3955393f5a'
down_revision = '9be253d75564'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.alter_column('card_number',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.alter_column('card_number',
               existing_type=sa.Numeric(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
